services:
  th-pys:
    build: .
    container_name: th-pys
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
