export const NOTIFICATION_TYPE = {
  INITIAL: "OptMVPVJ6RI",
  DAILY_REMINDER: "OptWWKP09A0",
  DUE_SOON: "OptG6AF1BOF",
  OVERDUE: "Opt3ZSXPDOL",
  REASSIGNMENT: "OptN2743A2J",
  EVIDENCE: "OptI5F6PS1O",
  REJECTED: "OptE9D011M5",
  EXCEPTION_CLOSE: "OptGJK6XKOU",
  TH_SUMMARY: "OptUBV63YAY",
} as const;

export const NOTIFICATION_RESULT = {
  PENDING: "OptCJS9N0AO",
  SENT: "OptCI84HFV4",
  ERROR: "OptWCZQEES2",
  SKIPPED: "Opt8VW2L87C",
} as const;
